### ISSUE TITLE
ERROR: Decoding downloaded file failed!

### ISSUE THREAD

**Issue by outbackdingo** [robseb/PiP2Bitbake#3]
python3 makePipRecipes.py

##############################################################################
#                                                                            #
#    ########   ######     ##    ##  #######   ######  ########  #######     #
#    ##     ## ##    ##     ##  ##  ##     ## ##    ##    ##    ##     ##    #
#    ##     ## ##            ####   ##     ## ##          ##    ##     ##    #
#    ########   ######        ##    ##     ## ##          ##    ##     ##    #
#    ##   ##         ##       ##    ##     ## ##          ##    ##     ##    #
#    ##    ##  ##    ##       ##    ##     ## ##    ##    ##    ##     ##    #
#    ##     ##  ######        ##     #######   ######     ##     #######     #
#                                                                            #
#            AUTOMATIC SCRIPT FOR GENERATING RECIPES TO INCLUDE              #
#           PYTHON PIP-PACKAGES TO YOUR YOCTO-PROJECT LINUX DISTO            #
#                                                                            #
#               by Robin Sebastian (https://github.com/robseb)               #
#                        Contact: git@robseb.de                              #
#                            Vers.: 1.2                                      #
#                                                                            #
##############################################################################

Type in the Name of the Python pip (PyPI) Package to include to your Yocto Project Linux Distro
Note: Consider the exact writing! Case sensitive!
You can find Python pip packages here: https://pypi.org/
PiP-Package Name: glances
Choose the requiered Python Version:
  Python 1-2: 1,2 
  Python 3  : 3   
Python Version:3
Type in the used License name for the recipe (e.g.: MIT)
License name: AGPL
Chosen License name: "AGPL"
Starting the generation...

--> Download for testing the Python PiP package
Collecting glances
  Using cached Glances-3.2.1.tar.gz (6.8 MB)
Saved ./makePipRec_workingFolder/Glances-3.2.1.tar.gz
Successfully downloaded glances

   The Name of the downloaded file: "Glances-3.2.1.tar.gz"
--> Calculate md5 checksum of this file
    md5sum = 1902c8649dfb4474ee8537bb297341ee
--> Calculate sha256sum checksum of this file
    sha256sum = 8ab984c711bd08711927884249392792d2e77a2e37bc21f77613412c5f7873c6
--> Decode the current Version Code of this PiP Package
--> ERROR: Decoding downloaded file failed!
    The file name must be in following syntax:
    <PiP Name>-<Version No.>.<File Suffix>

**Comment by bhupiister** [comment]
How did you solve this?

**Comment by outbackdingo** [comment]
hrmm mate this was 2 years ago... not sure i recall. i can go through it again over the weekend
